#!/bin/bash

# Replaces the remote production database with the local development database.
# Use this after updating data from a new source.

LOCAL_DATABASE=hvadbrugespengenetil_development

dropdb --if-exists -i $LOCAL_DATABASE
npx heroku pg:pull DATABASE_URL $LOCAL_DATABASE --remote production
