#!/bin/bash

# Replaces the local development database with the actual database from
# production.

LOCAL_DATABASE=hvadbrugespengenetil_development

heroku pg:reset DATABASE_URL --remote production
heroku pg:push $LOCAL_DATABASE DATABASE_URL --remote production
